version: '3.1'
services:
  api:
    container_name: nestjs-graphql-api
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src

  db:
    container_name: nestjs-graphql-db
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db_graphql'
