version: '3.1'
services:
  api:
    container_name: nestjs-graphql-api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/src

  db:
    container_name: nestjs-graphql-db
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
